In [14]:
import numpy as np
import math
import random as rand
from numpy import linalg as LA

In [2]:
rand.seed()
rand.randint(0,5)

1

In [3]:
#small_df = pd.read_csv('CS205_small_testdata__3.txt', sep="  ",header=None)
#large_df = pd.read_csv('CS205_large_testdata__36.txt', sep="  ",header=None)

small = np.loadtxt("CS205_small_testdata__3.txt")
large = np.loadtxt('CS205_large_testdata__36.txt')

In [4]:
# This is a testing stub to make sure that the search is working correctly
def acc_class(ftr):
    return(rand.randint(0,50))

In [29]:
small

array([[ 2.        , -0.11385477, -0.45279377, ...,  0.26205772,
         0.50386084,  0.67157231],
       [ 2.        ,  0.02937927,  0.75751174, ...,  0.02912671,
        -0.76236389,  0.04549898],
       [ 2.        ,  0.22602757, -1.5502071 , ..., -0.82138724,
        -0.00699236,  1.3225128 ],
       ...,
       [ 2.        , -0.29006101,  3.3876522 , ..., -0.19810085,
        -2.3249229 , -1.900013  ],
       [ 2.        , -0.45589562,  3.2123917 , ..., -1.2869598 ,
        -0.81692841,  0.66874778],
       [ 1.        , -0.06730446,  1.0165715 , ...,  1.8883417 ,
        -1.3469695 ,  1.0281039 ]])

In [6]:
for j in range(1,len(small[1,:])): print(j)

1
2
3
4
5
6
7
8
9
10


In [30]:
def ftr_search(mat):
    # List to keep track of all the current features
    crnt_ftr = []
    levels_best = []
    
    # Each level of the search tree
    for i in range(1,len(mat[1,:])):
        # List to keep track of the added feature
        add_ftr = -1
        # Keeps track of the best accuracy
        best_acc = -1
        print("On the", i, "th level of the search tree")
        
        # At each level, we want to see which features we can add
        for j in range(1,len(mat[1,:])):
            #print(j)
            #print(crnt_ftr)
            # At each level, I want to test the accuracy of adding a certain feature
            # but I don't want to consider a feature that's already included
            if j not in crnt_ftr:
                #print("  Considering adding the ", j, "feature")
                # Calculate the accuracy for the given set of features
                acc = knn_lv1out(mat, crnt_ftr, j)
                #acc = acc_class(j)
                # Checking if we should add this feature based on how it compares
                # to the best accuracy so far.
                #print(best_acc,acc)
                if acc > best_acc:
                    best_acc = acc
                    add_ftr = j # This is always updated when the accuracy is better.
                #print(add_ftr)
                
        # After we check all the features that we can add at this level
        # we want to make the current feature set is updated based on the best feature   
        crnt_ftr.append(add_ftr) 
        # The best combination of features and its accuracy at the current level
        levels_best.append((best_acc,crnt_ftr[:]))  # [:] is a copy of what is in the list now
        #print(add_ftr)
        print("*On level ", i, "added feature", add_ftr, "to current set*")
        #print(crnt_ftr)
        #print(crnt_ftr)
        #print(len(set(crnt_ftr)))
    return(levels_best)

In [20]:
a = np.arange(9) - 4
print(a)
b = a.reshape((3, 3))
b
LA.norm()

[-4 -3 -2 -1  0  1  2  3  4]


array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [24]:
# Creating a function that will perform kNN
def knn(mat, crnt_set_, new_ftr):
    '''
    '''
    # Keep track of accuracy
    acc = 0
    # The features that will be used for classification
    crnt_set = crnt_set_[:]
    crnt_set.append(new_ftr)
    #print(crnt_set)
  
    # Leave one out cross validation for each of the observations
    # with K = 1 nearest neighbors
    for i in range(0,len(mat)):
        # The observation to classify
        obs = mat[i,crnt_set]
        obs_label = mat[i,0]
        # An initial value for the distance that will be updated
        # if the distance at some iteration is smaller than the previous 
        # smallest distance.
        nn_dist = 1000000
        # Variable to keep track of the index that's closest to obs.
        nn_ind = 0
        # Now we compare each observation to the rest
        for j in range(0,len(mat)):
            # A check to make sure that the function is working properly
            # print("Ask if", i, "is nearest neighbor with", j)
            if j != i: # don't compare observation to itself
                #print(len(obs),len(mat[j,crnt_set]))
                #print(obs, mat[j,crnt_set])
                #dist = math.sqrt(sum(obs-mat[j,crnt_set])**2)
                # Calculates the 2-norm for the difference which is the euclidean distance.
                dist = LA.norm(obs-mat[j,crnt_set])
                #print(dist,nn_dist)
                if dist < nn_dist: # update label if this is true
                    nn_dist = dist
                    nn_ind = j
                    label = mat[j,0] # the label of the closest observation
                    
        # After finding the best label, check whether it was classified correctly
        if label == obs_label:
            acc = acc + 1
            
    acc_rate = acc/len(mat)
    return(acc_rate)

In [65]:
# Creating a function that will perform kNN
def knn_lv1out(mat, crnt_set_, new_ftr):
    '''
    '''
    # Keep track of accuracy
    acc = 0
    # The features that will be used for classification
    crnt_set = crnt_set_[:]
    crnt_set.append(new_ftr)
    #print(crnt_set)
 
    # Leave one out cross validation for each of the observations
    # with K = 1 nearest neighbors
    for i in range(0,len(mat)):
        # The observation to classify
        obs = mat[i,crnt_set]
        # An initial value for the distance that will be updated
        # if the distance at some iteration is smaller than the previous
        # smallest distance.
        nn_dist = 1000000
        # Variable to keep track of the index that's closest to obs.
        nn_ind = 0
        # Now we compare each observation to the rest
#         print(obs.shape)
#         print(mat[:,crnt_set].shape)
#         print((obs-mat[:,crnt_set]).shape)
        dist = LA.norm(obs-mat[:,crnt_set], axis=1)
        ind = np.ones(dist.shape[0],bool); ind[i] = False;  #print(dist[ind].shape)
#         print(np.min(dist[ind]))
#         print(np.argmin(dist[ind]))
        closest_idx = np.argmin(dist[ind])
        if mat[i,0] == mat[closest_idx, 0]: acc += 1
    return(acc/len(mat))

In [66]:
import datetime
print(datetime.datetime.now().time())
# Testing the ftr_search function with the small dataset
ftr_search(small)
print(datetime.datetime.now().time())

11:46:29.824729
On the 1 th level of the search tree
*On level  1 added feature 4 to current set*
On the 2 th level of the search tree
*On level  2 added feature 6 to current set*
On the 3 th level of the search tree
*On level  3 added feature 3 to current set*
On the 4 th level of the search tree
*On level  4 added feature 5 to current set*
On the 5 th level of the search tree
*On level  5 added feature 9 to current set*
On the 6 th level of the search tree
*On level  6 added feature 1 to current set*
On the 7 th level of the search tree
*On level  7 added feature 7 to current set*
On the 8 th level of the search tree
*On level  8 added feature 2 to current set*
On the 9 th level of the search tree
*On level  9 added feature 10 to current set*
On the 10 th level of the search tree
*On level  10 added feature 8 to current set*
11:46:31.020572


In [ ]:
print(datetime.datetime.now().time())
start = time.time()
# Testing the ftr_search function with the large dataset
acc_large = ftr_search(large)
end = time.time()
temp = end-start
print(temp)
hours = temp//3600
temp = temp - 3600*hours
minutes = temp//60
seconds = temp - 60*minutes
print('%d:%d:%d' %(hours,minutes,seconds))
print(f"--- {(time.time() - start)/60:.4f} minutes ---")
print(datetime.datetime.now().time())

11:47:03.703680
On the 1 th level of the search tree
*On level  1 added feature 93 to current set*
On the 2 th level of the search tree
*On level  2 added feature 129 to current set*
On the 3 th level of the search tree
*On level  3 added feature 56 to current set*
On the 4 th level of the search tree
*On level  4 added feature 41 to current set*
On the 5 th level of the search tree
*On level  5 added feature 152 to current set*
On the 6 th level of the search tree
*On level  6 added feature 225 to current set*
On the 7 th level of the search tree
*On level  7 added feature 44 to current set*
On the 8 th level of the search tree
*On level  8 added feature 238 to current set*
On the 9 th level of the search tree
*On level  9 added feature 218 to current set*
On the 10 th level of the search tree
*On level  10 added feature 95 to current set*
On the 11 th level of the search tree
*On level  11 added feature 9 to current set*
On the 12 th level of the search tree
*On level  12 added featu

*On level  97 added feature 235 to current set*
On the 98 th level of the search tree
*On level  98 added feature 175 to current set*
On the 99 th level of the search tree
*On level  99 added feature 192 to current set*
On the 100 th level of the search tree
*On level  100 added feature 106 to current set*
On the 101 th level of the search tree
*On level  101 added feature 148 to current set*
On the 102 th level of the search tree
*On level  102 added feature 145 to current set*
On the 103 th level of the search tree
*On level  103 added feature 147 to current set*
On the 104 th level of the search tree
*On level  104 added feature 247 to current set*
On the 105 th level of the search tree
*On level  105 added feature 7 to current set*
On the 106 th level of the search tree
*On level  106 added feature 111 to current set*
On the 107 th level of the search tree
*On level  107 added feature 34 to current set*
On the 108 th level of the search tree
*On level  108 added feature 71 to curre

In [49]:
import time
print(datetime.datetime.now().time())
start = time.time()
# Testing the ftr_search function with the large dataset
acc_small = ftr_search(small)
end = time.time()
temp = end-start
print(temp)
hours = temp//3600
temp = temp - 3600*hours
minutes = temp//60
seconds = temp - 60*minutes
print('%d:%d:%d' %(hours,minutes,seconds))
print(f"--- {(time.time() - start):.4f} seconds ---")
print(datetime.datetime.now().time())

11:30:03.740120
On the 1 th level of the search tree
*On level  1 added feature 4 to current set*
On the 2 th level of the search tree
*On level  2 added feature 6 to current set*
On the 3 th level of the search tree
*On level  3 added feature 3 to current set*
On the 4 th level of the search tree
*On level  4 added feature 5 to current set*
On the 5 th level of the search tree
*On level  5 added feature 9 to current set*
On the 6 th level of the search tree
*On level  6 added feature 1 to current set*
On the 7 th level of the search tree
*On level  7 added feature 7 to current set*
On the 8 th level of the search tree
*On level  8 added feature 2 to current set*
On the 9 th level of the search tree
*On level  9 added feature 10 to current set*
On the 10 th level of the search tree
*On level  10 added feature 8 to current set*
1.0707190036773682
0:0:1
--- 1.0716 seconds ---
11:30:04.815560


In [62]:
type(1)

int

In [293]:
print(combs)
combs.sort()   # Sort by the first element in the tuple first
print(combs)


[(40, [4]), (42, [4, 6]), (38, [4, 6, 3]), (50, [4, 6, 3, 5]), (36, [4, 6, 3, 5, 0]), (40, [4, 6, 3, 5, 0, 1]), (46, [4, 6, 3, 5, 0, 1, 2]), (44, [4, 6, 3, 5, 0, 1, 2, 9]), (39, [4, 6, 3, 5, 0, 1, 2, 9, 8]), (11, [4, 6, 3, 5, 0, 1, 2, 9, 8, 10]), (28, [4, 6, 3, 5, 0, 1, 2, 9, 8, 10, 7])]
[(11, [4, 6, 3, 5, 0, 1, 2, 9, 8, 10]), (28, [4, 6, 3, 5, 0, 1, 2, 9, 8, 10, 7]), (36, [4, 6, 3, 5, 0]), (38, [4, 6, 3]), (39, [4, 6, 3, 5, 0, 1, 2, 9, 8]), (40, [4]), (40, [4, 6, 3, 5, 0, 1]), (42, [4, 6]), (44, [4, 6, 3, 5, 0, 1, 2, 9]), (46, [4, 6, 3, 5, 0, 1, 2]), (50, [4, 6, 3, 5])]


In [104]:
# testing the kNN \function on the small dataset with all featuers
knn(mat = small, crnt_set, new_ftr)

0.7133333333333334

In [74]:
int(sum(small[1,1:]-small[2,1:]))**2

25

In [262]:
sum(small[1,[1,2]]-small[2,[1,2]])**2

4.456618812189467

In [105]:
small[1,[1,2,3]]

array([ 0.02937927,  0.75751174, -0.57226014])

In [110]:
len(small[1,-0])

TypeError: object of type 'numpy.float64' has no len()

In [108]:
for i in range(0,10): print(i)

0
1
2
3
4
5
6
7
8
9


In [111]:
small[1,-0]

2.0

In [134]:
l.append(1)

AttributeError: 'int' object has no attribute 'append'

In [316]:
for j in range(,5): print(j)

0
1
2
3
4
